---
name: cf-redis
director_uuid: REPLACE_WITH_DIRECTOR_ID

releases:
- name: cf-redis
  version: latest

compilation:
  workers: 2
  network: services1
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m3.medium

update:
  canaries: 1
  canary_watch_time: 30000-180000
  update_watch_time: 30000-180000
  max_in_flight: 4

networks:
- name: services
  type: manual
  subnets:
  - range: 10.10.32.0/24
    gateway: 10.10.32.1
    # Amazon reserves the first four IPs and the last IP for networking purposes
    reserved:
    - 10.10.32.2 - 10.10.32.4
    - 10.10.32.11
    - 10.10.32.5
    - 10.10.32.254
    static:
    - 10.10.32.6 - 10.10.32.10
    - 10.10.32.12
    dns:
    - 10.10.0.6
    cloud_properties:
      subnet: REPLACE_WITH_SUBNET_ID
- name: vip_network
  type: vip
  # Fake network properties to satisfy bosh diff
  subnets:
  - range: 127.0.99.0/24
    gateway: 127.0.99.1
    dns:
    - 127.0.99.250
  cloud_properties:
    security_groups:
    - bosh

resource_pools:
- name: services-small
  network: services
  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: m3.medium

jobs:
  - name: cf-redis-broker
    templates:
    - name: cf-redis-broker
      release: cf-redis
    - name: syslog-configurator
      release: cf-redis
    instances: 1
    resource_pool: services-small
    persistent_disk: 4096
    networks:
    - name: services
      static_ips:
      - 10.10.32.12

  - name: dedicated-node
    templates:
    - name: dedicated-node
      release: cf-redis
    - name: syslog-configurator
      release: cf-redis
    instances: 5
    resource_pool: services-small
    persistent_disk: 4096
    networks:
    - name: services
      static_ips:
      - 10.10.32.6
      - 10.10.32.7
      - 10.10.32.8
      - 10.10.32.9
      - 10.10.32.10

  - name: broker-registrar
    instances: 1
    lifecycle: errand
    networks:
    - name: services
    resource_pool: services-small
    templates:
    - name: broker-registrar
      release: cf-redis

  - name: broker-deregistrar
    instances: 1
    lifecycle: errand
    networks:
    - name: services
    resource_pool: services-small
    templates:
    - name: broker-deregistrar
      release: cf-redis

properties:
  broker:
    name: redis
    host: REPLACE_WITH redis-broker.<CF_APP_DOMAIN>
    username: admin
    password: REPLACE_WITH_BROKER_PASSWORD
  syslog_aggregator:
    address: REPLACE_WITH_SYSLOG_AGGREGATOR_HOST
    port: REPLACE_WITH_SYSLOG_AGGREGATOR_PORT
  cf:
    api_url: REPLACE_WITH_CLOUD_FOUNDRY_TARGET
    admin_username: REPLACE_WITH_CLOUD_FOUNDRY_ADMIN_USERNAME
    admin_password: REPLACE_WITH_CLOUD_FOUNDRY_ADMIN_PASSWORD
    nats:
      host: REPLACE_WITH_NATS_HOST
      port: REPLACE_WITH_NATS_PORT
      username: REPLACE_WITH_NATS_USERNAME
      password: REPLACE_WITH_NATS_PASSWORD
  redis:
    host: 10.10.32.12
    broker:
      network: services
      service_instance_limit: 5
      dedicated_nodes:
      - 10.10.32.6
      - 10.10.32.7
      - 10.10.32.8
      - 10.10.32.9
      - 10.10.32.10
      auth:
        username: admin
        password: REPLACE_WITH_BROKER_PASSWORD
