aws-cli/awscli-bundle.zip:
  size: 5207424
  object_id: 0221dcb3-3ce0-44e6-8c4f-c5c2abf1b0eb
  sha: db33b4740a670c9fb3bc5515cd7f9861fa1b1b13
ginkgo/ginkgo:
  size: 10583320
  object_id: 375645ba-af16-4ced-67aa-9f14a03f7c18
  sha: e5697ace4ec310cc6bc1ac157b26dd254faa93ac
nginx/nginx-1.8.0.tar.gz:
  size: 832104
  object_id: 77904c0d-6bb2-4e3e-b981-16828770f7a2
  sha: 12bad312764feae50246685ab2e74512d1aa9b2f
redis/redis-4.0.11.tar.gz:
  size: 1739656
  object_id: 3bce5585-a509-4f9e-7211-2c914ad5d2d4
  sha: a13ccf0f7051f82dc1c979bd94f0b9a9ba039122
redis/redis-5.0.2.tar.gz:
  size: 1952989
  object_id: c271cfc5-46cd-4d8d-7265-c0d717d6ffc2
  sha: 0dd182d33f55b8f7460a6c1822614573aece696c
ruby/bundler-1.3.5.gem:
  size: 268800
  object_id: 67d8e9d8-a79a-4ebe-8061-9ac59d0224b5
  sha: 2cad3052a59b83f1f616e8202f5c714e46bd8523
ruby/ruby-2.1.5.tar.gz:
  size: 15127433
  object_id: 698d02c7-61f9-4d14-893a-f4a8f085fc92
  sha: 9c0a238bd7839a4b51871641945a3da90997b8c2
ruby/rubygems-2.1.11.tgz:
  size: 367166
  object_id: a043d80c-896d-4165-b81f-a922a7817a33
  sha: ca3033432cae28deb7ced79cda271cb292b70e59
ruby/yaml-0.1.5.tar.gz:
  size: 504897
  object_id: b31f889b-5ae8-42ac-b6f1-f66b7126c784
  sha: 8b78cb9f759c7d80db8a7328c0ebecfe34fde737
