---
director_uuid: ((director_uuid))
name: ((deployment_name))

instance_groups:
- instances: 1
  name: cf-redis-broker
  azs: [((default_az))]
  networks:
  - name: ((default_network))
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk_type: ((default_persistent_disk_type))
  properties:
    route_registrar:
      routes:
      - health_check:
          name: ((broker_name))
          script_path: /var/vcap/jobs/cf-redis-broker/bin/health_check.sh
        name: broker_0
        port: 12350
        registration_interval: 10s
        tags:
          component: redis-broker
          env: production
        uris:
        - ((broker_name)).((system_domain))
  jobs:
  - name: cf-redis-broker
    release: cf-redis
  - name: route_registrar
    release: routing
    consumes:
      nats: {from: nats, deployment: "((cf_deployment_name))"}
  - name: syslog_forwarder
    release: syslog-migration
    properties: &syslog-configuration
      syslog:
        address: ((syslog_endpoint_host))
        port: ((syslog_endpoint_port))
        transport: tcp
        migration:
          message_format: job_index_id
          cleanup_conf_files:
          - 00-syslog_forwarder.conf
          - 05-syslog_forwarder.conf
  - name: broker-registrar
    release: cf-redis
  - name: broker-deregistrar
    release: cf-redis
  - name: smoke-tests
    release: cf-redis

- instances: ((dedicated_node_count))
  name: dedicated-node
  azs: [((default_az))]
  vm_type: ((default_vm_type))
  networks:
  - name: ((default_network))
  persistent_disk_type: ((default_persistent_disk_type))
  stemcell: default
  jobs:
  - name: dedicated-node
    release: cf-redis
  - name: syslog_forwarder
    release: syslog-migration
    properties: *syslog-configuration
  - name: permissions-tests
    release: redis-test
    properties:
      mode: dedicated-node

properties:
  broker:
    host: ((broker_name)).((system_domain))
    name: ((broker_name))
    password: ((broker_password))
    username: ((broker_username))
  cf:
    admin_username: ((cf_username))
    admin_password: ((cf_password))
    api_url: https://api.((system_domain))
    apps_domain: ((apps_domain))
    system_domain: ((system_domain))
  redis:
    agent:
      backend_port: 54321
    bg_save_command: yetanotherrandomstring
    broker:
      auth:
        password: ((broker_password))
        username: ((broker_username))
      backend_port: 12345
      dedicated_vm_plan_id: ((dedicated_vm_plan_id))
      enable_service_access: true
      name: ((broker_name))
      network: ((default_network))
      route_name: ((broker_name))
      service_id: ((service_id))
      service_instance_limit: 5
      dedicated_node_count: ((dedicated_node_count))
      service_name: ((service_name))
      shared_vm_plan_id: ((shared_vm_plan_id))
      subdomain: ((broker_name))
    config_command: configalias
    maxmemory: 262144000
    save_command: anotherrandomstring
  retry:
    backoff: linear
    baseline_interval_milliseconds: 1000
    max_attempts: 10

releases:
- name: cf-redis
  version: latest
- name: routing
  version: 0.162.0
- name: syslog-migration
  version: 9
- name: redis-test
  version: latest

stemcells:
- alias: default
  os: ((stemcell_os))
  version: "((stemcell_version))"

update:
  canaries: 1
  canary_watch_time: 30000-180000
  max_in_flight: 6
  update_watch_time: 30000-180000
