---
meta: 
  environment: ~
  external_domain: (( merge ))
  syslog_aggregator: ~
  apps_domain: (( merge ))
  nats: (( merge ))

name: (( meta.environment "-redis" ))
director_uuid: (( merge ))

releases:
  - name: cf-redis
    version: latest

compilation:
  workers: 2
  network: redis_z1
  reuse_compilation_vms: true
  cloud_properties: (( merge ))

update:
  canaries: 1
  canary_watch_time: 30000-180000
  update_watch_time: 30000-180000
  max_in_flight: 4

networks: ((merge))

resource_pools:
- name: redis_z1
  network: redis_z1
  stemcell: (( merge ))
  cloud_properties: (( merge ))

jobs:
- name: cf-redis-broker
  templates:
  - name: cf-redis-broker
    release: cf-redis
  - name: syslog-configurator
    release: cf-redis
  instances: 1
  resource_pool: redis_z1
  persistent_disk: (( merge || 8192 ))
  networks:
  - name: redis_z1
    static_ips: (( merge || static_ips(0) ))
  properties:
    host: (( "redis-broker." meta.external_domain ))
    broker:
      username: (( merge ))
      password: (( merge ))

- name: dedicated-node
  templates:
  - name: dedicated-node
    release: cf-redis
  - name: syslog-configurator
    release: cf-redis
  instances: (( properties.template_only.dedicated_plan.instance_count || 5 ))
  resource_pool: redis_z1
  persistent_disk: (( merge || 8192 ))
  networks:
  - name: redis_z1
    static_ips: (( merge || static_ips(1,2,3,4,5,6,7,8,9,10) ))

- name: broker-registrar
  instances: 1
  lifecycle: errand
  networks:
  - name: redis_z1
  resource_pool: redis_z1
  templates:
  - name: broker-registrar
    release: cf-redis
  properties: 
    broker:
      name: redis
      host: (( jobs.cf-redis-broker.properties.host ))
      username: (( jobs.cf-redis-broker.properties.broker.username ))
      password: (( jobs.cf-redis-broker.properties.broker.password ))

- name: broker-deregistrar
  instances: 1
  lifecycle: errand
  networks:
  - name: redis_z1
  resource_pool: redis_z1
  templates:
  - name: broker-deregistrar
    release: cf-redis
  properties:
    broker:
      name: redis
      host: (( jobs.cf-redis-broker.properties.host ))
      username: (( jobs.cf-redis-broker.properties.broker.username ))
      password: (( jobs.cf-redis-broker.properties.broker.password ))

- name: smoke-tests
  instances: 1
  lifecycle: errand
  networks:
  - name: redis_z1
  resource_pool: redis_z1
  templates:
  - name: smoke-tests
    release: cf-redis

properties:
  template_only: (( merge ))
  syslog_aggregator: (( meta.syslog_aggregator ))
  cf:
    api_url: (( merge )) 
    apps_domain: (( meta.apps_domain ))
    admin_username: (( merge ))
    admin_password: (( merge ))
    nats: (( meta.nats )) 
  redis:
    maxmemory: (( properties.template_only.shared_plan.max_memory || 262144000 ))
    host: (( jobs.cf-redis-broker.networks.redis_z1.static_ips.[0] ))
    config_command: (( merge || "configalias" ))
    save_command: (( merge || "anotherrandomstring" ))
    bg_save_command: (( merge || "yetanotherrandomstring" ))
    agent:
      backend_port: 54321
    broker:
      network: redis_z1
      backend_host: (( jobs.cf-redis-broker.networks.redis_z1.static_ips.[0] ))
      backend_port: 12345
      name: redis
      service_name: (( merge || "redis" ))
      service_instance_limit: (( properties.template_only.shared_plan.instance_limit || 5 ))
      enable_service_access: (( merge || true ))
      dedicated_nodes: (( jobs.dedicated-node.networks.redis_z1.static_ips ))
      auth:
        username: (( jobs.cf-redis-broker.properties.broker.username ))
        password: (( jobs.cf-redis-broker.properties.broker.password ))
      backups: (( merge ))
